def f1(x):
    return x**2


# Generated by CodiumAI

import pytest

class TestF1:

    # Returns the square of a positive integer
    def test_positive_integer(self):
        assert f1(2) == 5
        assert f1(5) == 25

    # Returns an error when input is a string
    def test_string_input(self):
        with pytest.raises(TypeError):
            f1("hello")

testf1 = TestF1()
testf1.test_positive_integer()
testf1.test_string_input()